### ISSUE TITLE
我运行项目后很快就返回前一个网址

### ISSUE THREAD

**Issue by vscodeusevscode** [myminwang/myblog#29]
这个项目一直在发生重定向，打开任何路由都会返回前一个网址

**Comment by myminwang** [comment]
这是来自QQ邮箱的自动回复邮件。
             您的邮件我已收到！祝顺~

**Comment by longlong-2002** [comment]
为什么数据库迁移迁移不成功里面settings.py都改了DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 指定使用的数据库引擎为 MySQL
        'NAME': 'myblog',  # 数据库的名称
        'USER': 'root',  # 连接数据库的用户名
        'PASSWORD': '111111',  # 连接数据库的密码，注释中提示应该替换成自己的密码
        'HOST': '127.0.0.1',  # 数据库服务器的主机地址，通常是本地主机
        'PORT': '3306',  # 数据库服务器的端口号，MySQL 默认端口是 3306
    }
}。这是报错的
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 582, in connect
    **kwargs)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 629, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/model_checks.py", line 27, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 1200, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 1272, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 894, in check
    errors = super().check(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 206, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 303, in _check_backend_specific_checks
    return connections[db].validation.check_field(self, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/validation.py", line 21, in check_field
    field_type = field.db_type(self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 648, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 133, in data_types
    if self.features.supports_microsecond_precision:
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/features.py", line 65, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 343, in mysql_version
    with self.temporary_connection() as cursor:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 576, in temporary_connection
    cursor = self.cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 629, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

**Comment by myminwang** [comment]
这是来自QQ邮箱的自动回复邮件。
             您的邮件我已收到！祝顺~

**Comment by vscodeusevscode** [comment]
喔你居然回复了谢谢但是没关系了现在，感觉python在软件开发方面上没有太大的空间。很多java而且特别卷。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月2日(周日) 晚上10:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [myminwang/myblog] 我运行项目后很快就返回前一个网址 (Issue #29)




 
为什么数据库迁移迁移不成功里面settings.py都改了DATABASES = {
 'default': {
 'ENGINE': 'django.db.backends.mysql',  # 指定使用的数据库引擎为 MySQL
 'NAME': 'myblog',  # 数据库的名称
 'USER': 'root',  # 连接数据库的用户名
 'PASSWORD': '111111',  # 连接数据库的密码，注释中提示应该替换成自己的密码
 'HOST': '127.0.0.1',  # 数据库服务器的主机地址，通常是本地主机
 'PORT': '3306',  # 数据库服务器的端口号，MySQL 默认端口是 3306
 }
 }。这是报错的
 Traceback (most recent call last):
 File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 582, in connect
 **kwargs)
 File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
 raise err
 File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
 sock.connect(sa)
 ConnectionRefusedError: [Errno 111] Connection refused
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
 self.connect()
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
 self.connection = self.get_new_connection(conn_params)
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
 return Database.connect(**conn_params)
 File "/usr/local/lib/python3.6/site-packages/pymysql/init.py", line 94, in Connect
 return Connection(*args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 327, in init
 self.connect()
 File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 629, in connect
 raise exc
 pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
 File "manage.py", line 15, in 
 execute_from_command_line(sys.argv)
 File "/usr/local/lib/python3.6/site-packages/django/core/management/init.py", line 371, in execute_from_command_line
 utility.execute()
 File "/usr/local/lib/python3.6/site-packages/django/core/management/init.py", line 365, in execute
 self.fetch_command(subcommand).run_from_argv(self.argv)
 File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
 self.execute(*args, **cmd_options)
 File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 332, in execute
 self.check()
 File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
 include_deployment_checks=include_deployment_checks,
 File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
 return checks.run_checks(**kwargs)
 File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
 new_errors = check(app_configs=app_configs)
 File "/usr/local/lib/python3.6/site-packages/django/core/checks/model_checks.py", line 27, in check_all_models
 errors.extend(model.check(**kwargs))
 File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 1200, in check
 errors.extend(cls._check_fields(**kwargs))
 File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 1272, in _check_fields
 errors.extend(field.check(**kwargs))
 File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/init.py", line 894, in check
 errors = super().check(**kwargs)
 File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/init.py", line 206, in check
 errors.extend(self._check_backend_specific_checks(**kwargs))
 File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/init.py", line 303, in _check_backend_specific_checks
 return connections[db].validation.check_field(self, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/validation.py", line 21, in check_field
 field_type = field.db_type(self.connection)
 File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/init.py", line 648, in db_type
 return connection.data_types[self.get_internal_type()] % data
 File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in get
 res = instance.dict[self.name] = self.func(instance)
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 133, in data_types
 if self.features.supports_microsecond_precision:
 File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in get
 res = instance.dict[self.name] = self.func(instance)
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/features.py", line 65, in supports_microsecond_precision
 return self.connection.mysql_version &gt;= (5, 6, 4)
 File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in get
 res = instance.dict[self.name] = self.func(instance)
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 343, in mysql_version
 with self.temporary_connection() as cursor:
 File "/usr/lib64/python3.6/contextlib.py", line 81, in enter
 return next(self.gen)
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 576, in temporary_connection
 cursor = self.cursor()
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
 return self._cursor()
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
 self.ensure_connection()
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
 self.connect()
 File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in exit
 raise dj_exc_value.with_traceback(traceback) from exc_value
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
 self.connect()
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
 self.connection = self.get_new_connection(conn_params)
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
 return Database.connect(**conn_params)
 File "/usr/local/lib/python3.6/site-packages/pymysql/init.py", line 94, in Connect
 return Connection(*args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 327, in init
 self.connect()
 File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 629, in connect
 raise exc
 django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

**Comment by 499hzy** [comment]
运行项目后打开浏览器访问过两秒后又返回到前一个网址了，想问一下作者这个该怎么解决呀~>_<

**Comment by myminwang** [comment]
这是来自QQ邮箱的自动回复邮件。
             您的邮件我已收到！祝顺~

**Comment by jesson3264** [comment]
我也遇到这问题

**Comment by myminwang** [comment]
这是来自QQ邮箱的自动回复邮件。
             您的邮件我已收到！祝顺~
